import type { ReactNode } from "react";

const groups = [{ label: "Workspace", items: [["Dashboard", "/dashboard"], ["Tasks", "/tasks"], ["Clients", "/clients"]] }, { label: "Operations", items: [["Agents", "/agents"], ["Communications", "/communications"], ["Content", "/content"], ["Finance", "/finance"]] }, { label: "System", items: [["Security", "/security"], ["Approvals", "/approvals"], ["Integrations", "/integrations"], ["Settings", "/settings"]] }] as const;
const mobile = [["Home", "/dashboard"], ["Agents", "/agents"], ["Tasks", "/tasks"], ["Security", "/security"], ["More", "/settings"]] as const;

export const AppShell = ({ path, onNavigate, children }: { path: string; onNavigate: (path: string) => void; children: ReactNode }): React.ReactElement => {
  const navigate = (event: React.MouseEvent<HTMLAnchorElement>, next: string) => { event.preventDefault(); onNavigate(next); };
  return <div className="app-shell"><aside className="sidebar"><div className="wordmark"><span className="brand-mark">J</span><span>JARVIS</span></div><p className="sidebar-caption">Executive operating system</p><nav>{groups.map((group) => <div className="nav-group" key={group.label}><p className="nav-label">{group.label}</p>{group.items.map(([label, href]) => <a className={path === href ? "nav-link active" : "nav-link"} href={href} key={href} onClick={(e) => navigate(e, href)}><span className="nav-dot" />{label}</a>)}</div>)}</nav><div className="sidebar-footer"><span className="status-dot" />Systems nominal</div></aside><div className="main-column"><header className="topbar"><div><p className="eyebrow">{new Intl.DateTimeFormat(undefined,{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date())}</p><p className="topbar-title">Good morning, Ganesh</p></div><div className="topbar-actions"><button className="icon-button" aria-label="Notifications">◎</button><button className="avatar" aria-label="Account">G</button></div></header><main className="content">{children}</main><nav className="mobile-nav">{mobile.map(([label, href]) => <a className={path === href ? "mobile-link active" : "mobile-link"} href={href} key={href} onClick={(e) => navigate(e, href)}><span className="mobile-icon">{label.slice(0, 1)}</span>{label}</a>)}</nav></div></div>;
};
